### PR TITLE
Custom color functions and jinja separate

### PR DESCRIPTION
**Pull request by deargle**
@sauln the two PRs merged (#149 and #152)

### CODE REVIEW

**Comment by sauln** [comment]
Thanks! Sorry for not getting back to you earlier. I'll review asap.

**Comment by deargle** [comment]
@sauln nw. I'm working on minifying css and js at the moment, so going to go back to preloading and injecting into render function instead of `include`ing.

**Comment by deargle** [comment]
@sauln any memory why this was closed -- was it just to tidy things up before JOSS submission?

**Comment by deargle** [comment]
Nevermind, I don't like the color function stuff that I did. I think it's better with the current approach of having the user specify the color function rather than giving kmapper a function to do it with. Although, `color_function` would be better-named `color_data`, since it's not a function at all, but rather, must be a 1d vector / list. 

Still might be useful to be able to customize the node color function -- current code always does `np.mean` on the color data for the given node. I may do that again, too.

**Comment by sauln** [comment]
I can't remember, sorry.  I'm definitely onboard with the better word choices and customizable function.  I'm not a big fan of the np.mean in many applications.

**Pull request closed without merging**
