### PR TITLE
decouple jinja from kmapper.visualize

### PR DESCRIPTION
**Pull request by deargle**
all template rendering is moved into the single render_template call. The biggest refactor for this was to no longer generate the html for each node tooltip-set in the `format_mapper_data` function loop.

I wanted to do this so that I could externally call `format_mapper_data` without needing the env and without the clutter of the html being stored in the python object. I wanted to easily extract the node color value for a csv output. I am moving towards creating a color_function approach which will allow for within_node coloring. But that is tricky with the tight coupling, so shifting things around a bit.

### CODE REVIEW

**Comment by deargle** [comment]
Hold up, node histograms are not updating on mouseover.

**Comment by sauln** [comment]
I'll have time to give a more thorough review next week. One thing I noticed real quick is you using jinja's include statements for the kmapper.js file. In the past we've had trouble because the source isn't included in the file, so if you move the generated html, the relative links break.  

Ideally we'ed could put a unit test together to test this. I'm not sure the best way to do that though. Maybe bring selenium into the mix?

**Comment by deargle** [comment]
@sauln jinja's `includes` _do_ pull in the source. Perhaps you are thinking of html `link` tags?

I've never used selenium -- I fly by the seat of my pants and do a visual inspection. Maybe a middle ground for testing the graphical output is a checklist of things to visually inspect for the d3 vis before merging a change that impacts the output.

I'm a web dev before a mathematician, so hopefully I'll be able to contribute more to the d3 stuff in the future.

**Comment by deargle** [comment]
kmapper.js embedded in the page source after loaded through jinja `includes`

image

**Comment by deargle** [comment]
Fixed the histograms. Converted some of the `include`s to `import`s because parameter-passing is more explicit than context passing, and context-passing wasn't working for a nested includes idk why.

**Comment by deargle** [comment]
Regarding testing the jinja build, we could also make it throw an error is a variable is missing. That would have caught the broken histograms I had earlier.

e.g., `env = jinja2.Environment(loader=<someloader>, undefined=jinja2.StrictUndefined)`

https://stackoverflow.com/a/11315494/5917194

**Comment by sauln** [comment]
Sounds good.  Is it possible to merge the two vis PRs and then I can dig into both at the same time? Early next week I'll have half a day to test everything out.

**Comment by deargle** [comment]
I hesitate to because the jinja one is relatively quite minor, while the
color one is enormous and sprawling. Color one may take more time and
iterations, but i plan to extend more off the javascript/html soon so id
prefer to have that merged first. If you'd really like though, i can merge
and create another branch on my fork / a third PR with the two combined?
Jinja PR really only substantially effects the tooltip-creation code in
visuals.py

**Comment by deargle** [comment]
See #158

**Pull request closed without merging**
