### PR TITLE
Typo fix in  Contributing document

### PR DESCRIPTION
**Pull request by leouieda**
Minor typo and missing formatting.

Also, why is there a copy of the Code of Conduct in this file?

openjournals/joss-reviews#1315

### CODE REVIEW

**Comment by sauln** [comment]
Thanks for catching that.  Re: the code of conduct, I can't remember why that's there. Since we have the code of conduct file, I've removed it from `contributing.md` in this PR.

**Comment by leouieda** [comment]
:+1: It might still be good to have a link in there, though. I tend to have this in my own projects:

```
## Ground Rules

The goal is to maintain a diverse community that's pleasant for everyone.
**Please be considerate and respectful of others**.
Everyone must abide by our [Code of Conduct](CODE_OF_CONDUCT.md) and we encourage all to
read it carefully.
```

**Comment by sauln** [comment]
That's a nice note, you mind if I copy-pasta?

**Comment by leouieda** [comment]
Not at all! Copy away

**Pull request merged**
