### PR TITLE
mutable arguments removed

### PR DESCRIPTION
**Pull request by cmorph1**
I have removed the mutable arguments, I haven't touched the Color_scale argument.

### CODE REVIEW

**Comment by sauln** [comment]
Looks good, thanks for doing this!

It looks like there are no tests that use the lens_names property. Would you mind adding one so we can be sure it is working correctly?

Thank you!

**Comment by cmorph1** [comment]
No problem, I will take  a look at this now.

**Comment by cmorph1** [comment]
I get the feeling I am going to sound stupid, but how do you add a test?

**Comment by sauln** [comment]
not at all! learning about tests is always a hard hurdle. 

In the source directory, you can install the test requirements into your environment with the command
```
pip install -e ".[testing]"
```

Then, you can run the test suite with the command

```
pytest test
```

You should see a summary of all the test runs showing that they've passed.

Then you can add a new test to the file `test/test_mapper.py` and try running the tests again. 

We use [pytest](https://docs.pytest.org/en/latest/) for all our tests, you can read more about it on their docs site and look at some of the other tests to see how we structure them.

Let me know if you need anything else!

**Comment by cmorph1** [comment]
Thanks I'll give it a go

**Comment by cmorph1** [comment]
When I am trying to run pytest test, I'm being told I need to:
`pip install python-igraph plotly ipywidgets`
But that fails when I try to install it. I'm not sure what my next move should be

**Comment by sauln** [comment]
Did running

```
pip install -e ".[testing]"
```

result in errors? That command should install those 3 packages. If that did not create errors, you might have a problem with your environments being crossed. Are you using virtual environments? 

Compare the output of `which pytest` and `which python`, making sure they are both pointing to similar places.

**Comment by cmorph1** [comment]
I got this error:
'Cannot find the C core of igraph on this system using pkg-config'
I've had workspace issues on this laptop with the virtual environments before. I've pip uninstalled everything on there and try creating another venv tomorrow. Thanks for your help!

**Comment by sauln** [comment]
Ahh, if you are on Windows you should follow the instructions here: https://igraph.org/python/

Sometimes setting igraph up can be a pain point.

If you still can't get it working, you can specify just running the test file you're extending with the command

```
pytest test/test_mapper.py
```

**Comment by cmorph1** [comment]
Thanks for the help Nathaniel, I'll have a go at this tonight.

**Comment by cmorph1** [comment]
I think I have done it. Let me know if I need to do anything more.

**Comment by sauln** [comment]
It looks like you've added a test, but it still has the body of the test you copied above. Maybe you need to make one more commit with the changes to the test?

**Comment by cmorph1** [comment]
Sorry I'll change this tonight.

**Comment by cmorph1** [comment]
The test is failing, but I think its down to how I've built it as I am getting this error:
">       if not len(graph["nodes"]) > 0:
E       IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"
I may need to install i-graph and get a better understanding of how it works.

**Comment by sauln** [comment]
igraph is a dependency for some of the visualization tools we use, but you shouldn't have to use it other than having it installed. 

It's hard to diagnose the issue without the code. Feel free to push what you have no and I can make edits if need be.

Thanks!

**Comment by cmorph1** [comment]
I'll have one last go at it tonight and if I can't work it out I'll push for you to review, thanks Nathaniel

**Comment by cmorph1** [comment]
Hi Nathaniel,
Unfortunately I'm lost. I tried to install the extra packages and had the following error:
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

When I try to run test_mapper I get this error:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I will push my test through to you. It would be a great help if you could explain what I have done wrong so I can learn from it.

**Pull request merged**
