### PR TITLE
Paper edits

### PR DESCRIPTION
**Pull request by deargle**
Regarding the choice of an image, I found these in the docs:

* [breast cancer](https://kepler-mapper.scikit-tda.org/examples.html#unsupervised-anomaly-detection)
* [TOR traffic](https://kepler-mapper.scikit-tda.org/notebooks/TOR-XGB-TDA.html#Image-of-output)
* [whatever the output of the newsgroup NLP vis is](https://kepler-mapper.scikit-tda.org/notebooks/KeplerMapper-Newsgroup20-Pipeline.html)
* [lead out strong with a gymnist horse (lol)](https://kepler-mapper.scikit-tda.org/notebooks/self-guessing.html#d-2)

   I vote for either the breast cancer one or the TOR traffic one.

And I haven't referenced the figure in the text yet...

### CODE REVIEW

**Comment by deargle** [comment]
Cool. I also had the thought that we could add to this sentence:

> The work of [@Lumetal2013] sparked widespread interest in the Mapper technique by demonstrating its use in multiple domains, including political science, biology, and sports analytics

with a few examples of specifically what insights it gave into polisci, biology, and sports analytics, like one each. Would increase power.

We could also add a note to the caption for Figure 1, saying what information can be gleaned from the visualization. Like, "the vis helps identify that there is a flare out here of high whatever likelihood, and examination of datapoints in that node reveal that they have _x_ characteristics." I dunno, but something showing how the vis leads to layperson info.

**Comment by sauln** [comment]
Ah sorry, it was probably a bit premature to merge this PR then.  Want to open a second one?

**Comment by deargle** [comment]
Sure. Prefer any goto visualizations from the docs for which a takeaway is
obvious? I can open a new pr with a stab at describing it. Diabetes good?

**Comment by sauln** [comment]
Which one is the diabetes viz? Is that in the examples somewhere? For obvious takeaways I've found it's easier with very simple examples like the two circles.

**Comment by deargle** [comment]
Sorry, I keep calling it diabetes, but I meant the breast cancer one,
linked in an earlier comment.

Feel free to counter this, but would you agree that the thing about the
circles one is that the finding isn't surprising to a layperson -- a
circles dataset makes a visualization with circles.

We could maybe ask for permission from one of the papers that has used
kepler mapper to reproduce their figure and cite their finding. E.g.
there's one that uses kepler mapper to flag a flare of datapoints with high
likelihood of manufacturing defects from an open source R dataset, then
explores attributes of those in the flare IIRC.

**Comment by sauln** [comment]
Yeah the breast cancer one is good. 

I do think the circles helps people gain an intuition of what to expect from mapper, it isn't surprising at all.

**Comment by deargle** [comment]
Is it correct to say that for the circles one, the color has no meaning, as the default color function is to average the item ids?

**Comment by sauln** [comment]
That might be the case. It depends on where you look. Many of the images were generated a long time ago, so things might have changed.

**Pull request merged**
